#!/bin/sh

case "$1" in
  start)
    echo "Starting potop service"
    /home/rura/gopotop.sh &
    /home/rura/govpot.sh &
    ;;
  stop)
    echo "Stopping potop service"
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  status)
    echo "Status potop"
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
esac

exit 0